"""Add OccurrenceReport model

Revision ID: 20fdc7fd9d0b
Revises: a831540800ed
Create Date: 2026-04-22 11:10:07.667817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fdc7fd9d0b'
down_revision = 'a831540800ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazard_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_no', sa.String(length=20), nullable=True),
    sa.Column('date_reported', sa.DateTime(), nullable=True),
    sa.Column('taxonomy_specific', sa.String(length=100), nullable=True),
    sa.Column('unsafe_event', sa.Text(), nullable=True),
    sa.Column('inherent_risk_score', sa.String(length=5), nullable=True),
    sa.Column('safety_actions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reporter_email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_no')
    )
    op.create_table('occurrence_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_no', sa.String(length=20), nullable=True),
    sa.Column('date_reported', sa.DateTime(), nullable=True),
    sa.Column('reporter_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('personnel_injured', sa.Text(), nullable=True),
    sa.Column('equipment_damaged', sa.Text(), nullable=True),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=1), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.String(length=5), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('feedback_given', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occurrence_report')
    op.drop_table('hazard_report')
    # ### end Alembic commands ###
