"""Add EmergencyResponsePlan model

Revision ID: 5acde339570d
Revises: b72515f4240b
Create Date: 2026-04-21 11:53:09.538904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acde339570d'
down_revision = 'b72515f4240b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_response_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PlanName', sa.String(length=100), nullable=False),
    sa.Column('LastDrillDate', sa.DateTime(), nullable=True),
    sa.Column('NextDrillDate', sa.DateTime(), nullable=False),
    sa.Column('Status', sa.Enum('ACTIVE', 'UNDER_REVIEW', 'NEEDS_DRILL', name='erpstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_response_plan')
    # ### end Alembic commands ###
