"""Add closure fields to OccurrenceReport

Revision ID: 5ec50593e03c
Revises: 20fdc7fd9d0b
Create Date: 2026-04-22 13:42:41.119038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec50593e03c'
down_revision = '20fdc7fd9d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residual_risk', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('actual_close_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_report', schema=None) as batch_op:
        batch_op.drop_column('actual_close_date')
        batch_op.drop_column('residual_risk')

    # ### end Alembic commands ###
