"""add closure_comment to OccurrenceReport

Revision ID: 7939421ad214
Revises: 981236be0738
Create Date: 2026-04-27 08:48:32.306865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7939421ad214'
down_revision = '981236be0738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closure_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_report', schema=None) as batch_op:
        batch_op.drop_column('closure_comment')

    # ### end Alembic commands ###
