"""Add AISL-SD-012 CAR fields

Revision ID: 981236be0738
Revises: 5ec50593e03c
Create Date: 2026-04-27 08:30:10.990992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981236be0738'
down_revision = '5ec50593e03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_cause', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('system_alteration', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resp_manager', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_report', schema=None) as batch_op:
        batch_op.drop_column('resp_manager')
        batch_op.drop_column('system_alteration')
        batch_op.drop_column('root_cause')

    # ### end Alembic commands ###
