"""add observations to erp

Revision ID: a831540800ed
Revises: 5acde339570d
Create Date: 2026-04-21 14:25:04.095731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a831540800ed'
down_revision = '5acde339570d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_response_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Observations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_response_plan', schema=None) as batch_op:
        batch_op.drop_column('Observations')

    # ### end Alembic commands ###
