"""Initial migration for Aviation SMS

Revision ID: b72515f4240b
Revises: 
Create Date: 2026-04-20 16:23:33.548346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72515f4240b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('install_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'OVERDUE', 'REMOVED', name='componentstatus'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('risk_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hazard_description', sa.Text(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('A', 'B', 'C', 'D', 'E'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EXTREME', name='risklevel'), nullable=False),
    sa.Column('mitigation_plan', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_assurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_date', sa.DateTime(), nullable=False),
    sa.Column('finding_details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Open', 'Closed'), nullable=True),
    sa.Column('next_audit_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('safety_objectives', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('implementation_status', sa.Enum('DRAFT', 'IMPLEMENTED', 'REVIEWED', name='safetypolicystatus'), nullable=True),
    sa.Column('manual_filename', sa.String(length=255), nullable=True),
    sa.Column('implementation_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('training_records', sa.Text(), nullable=True),
    sa.Column('date_published', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety_promotion')
    op.drop_table('safety_policy')
    op.drop_table('safety_assurance')
    op.drop_table('risk_assessment')
    op.drop_table('component')
    op.drop_table('user')
    # ### end Alembic commands ###
