"""Add missing OccurrenceReport columns for AISL-SD-012/017

Revision ID: f73177146884
Revises: 7939421ad214
Create Date: 2026-04-27 11:01:46.353101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73177146884'
down_revision = '7939421ad214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_report', schema=None) as batch_op:
        batch_op.drop_column('feedback_date')
        batch_op.drop_column('reporter_feedback')

    # ### end Alembic commands ###
